apiVersion: apps/v1
kind: Deployment
metadata:
  name: irisapp
spec:
  selector:
    matchLabels:
      app: irisapp
  template:
    metadata:
      labels:
        app: irisapp
    spec:
      containers:
      - name: iris
        image: harshdupare/irisclass:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: irisapp-service
spec:
  selector:
    app: irisapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort

